myonaingwinn/webrtc-laravel

backend/database/seeders/DatabaseSeeder.php
backend/database/seeders/UserSeeder.php

- add UserSeeder in database/seeders
- update DatabaseSeeder file
**### To Do**
- run "php artisan db:seed" in backend

add seeder for database

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/assets/styles/Header/header.scss
frontend/src/assets/styles/Home/home.scss
frontend/src/assets/styles/Room/create_room.scss
frontend/src/assets/styles/Room/room_list.scss
frontend/src/assets/styles/Sider/sider.scss
frontend/src/assets/styles/User/user_list.scss
frontend/src/assets/styles/main.scss
frontend/src/components/Header/Header.js
frontend/src/components/Home/Home.js
frontend/src/components/Room/CreateRoom.js
frontend/src/components/Room/RoomList.js
frontend/src/components/Sider/Sider.js
frontend/src/components/User/UserList.js
frontend/src/index.js

Add : Header, Sider and Templates

---

frontend/src/components/Register/Register.js

- replace api route with baseUrl in register form

update baseUrl in register form

---

frontend/src/components/Sider/Sider.js

update : sider with Links

---

frontend/public/index.html
frontend/src/assets/styles/Login/login.scss
frontend/src/assets/styles/Register/register.scss
frontend/src/assets/styles/main.scss
frontend/src/components/Login/Login.js
frontend/src/components/Register/Register.js

- remove disable in login form
- add notification in login and register form
- change form design in login and register form
Resolve #29

add notification message and change form design in login and register

---

frontend/src/assets/styles/Header/header.scss
frontend/src/components/Header/Header.js

Add : logo and logged in user to header

---

frontend/src/assets/styles/Header/header.scss
frontend/src/components/Header/Header.js

add : App name

---

frontend/src/assets/styles/Chat/group_chat.scss
frontend/src/assets/styles/main.scss
frontend/src/components/Chat/GroupChat.js
frontend/src/components/Room/CreateRoom.js
frontend/src/components/Room/Room.js
frontend/src/helpers/Utilities.js
server/package-lock.json
server/package.json
server/server.js

add: group chat

---

frontend/src/components/Room/RoomComponent.js
server/server.js

fix : update rooms in list

---

backend/app/Http/Controllers/api/v1/UserController.php
backend/app/Models/User.php
backend/database/migrations/2014_10_12_000000_create_users_table.php
backend/database/seeders/UserSeeder.php

solve #60 
- add uuid column in user table
- generate uuid in user controller 
- update register method in user controller
- update userseeder file
****
- php artisan migrate:refresh
- php artisan db:seed

generate uuid and add to user table

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/assets/styles/Error/empty.scss
frontend/src/assets/styles/Home/home.scss
frontend/src/assets/styles/Room/create_room.scss
frontend/src/assets/styles/Room/room.scss
frontend/src/assets/styles/Room/room_list.scss
frontend/src/assets/styles/User/user_list.scss
frontend/src/assets/styles/common.scss
frontend/src/assets/styles/main.scss
frontend/src/components/Chat/GroupChat.js
frontend/src/components/Error/Empty.js
frontend/src/components/Header/Header.js
frontend/src/components/Home/Home.js
frontend/src/components/Loading/Loading.js
frontend/src/components/Login/Login.js
frontend/src/components/Room/CreateRoom.js
frontend/src/components/Room/RoomComponent.js
frontend/src/components/Room/RoomList.js
frontend/src/components/Sider/Sider.js
frontend/src/components/User/User.js
frontend/src/components/User/UserList.js
frontend/src/helpers/SocketClient.js
frontend/src/index.js
frontend/src/store/index.js
server/server.js

Add : Online User List

---

frontend/src/components/Header/Header.js
frontend/src/components/User/User.js
frontend/src/helpers/Utilities.js

add : avator color for each user

---

frontend/src/assets/styles/Room/room_component.scss
frontend/src/assets/styles/Room/room_list.scss
frontend/src/components/Room/CreateRoom.js
frontend/src/components/Room/RoomComponent.js

add description field

---

frontend/src/assets/styles/Room/create_room.scss
frontend/src/assets/styles/Room/room_component.scss
frontend/src/components/Room/CreateRoom.js
frontend/src/components/Room/RoomComponent.js
server/server.js

set join button disable

---

frontend/src/components/Login/Login.js
frontend/src/helpers/Utilities.js

replace id with uuid in Utilities file and Login.js

---

frontend/src/components/User/User.js
frontend/src/components/User/UserList.js
frontend/src/helpers/SocketClient.js
server/server.js

##This is Peer Call
resolve #76

Add: Peer Call

---

frontend/public/index.html

- update app title in index.html

Update App Title

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/assets/styles/PrivateChat/private_chat.scss
frontend/src/assets/styles/main.scss
frontend/src/components/PrivateChat/PrivateChat.js
frontend/src/components/User/User.js
frontend/src/components/User/UserList.js
server/server.js

add : P2PChat

---

frontend/src/components/Room/RoomList.js
frontend/src/components/Sider/Sider.js

fix : sider menu, create room click

---

frontend/src/assets/styles/Chat/private_chat.scss
frontend/src/assets/styles/common.scss
frontend/src/components/Chat/PrivateChat.js

Update : P2P Chat UI
